version: "2"
services:
  vc_data:
    image: alpine:latest
    container_name: vc_data
    volumes:
      - ./conf/conf.d:/etc/nginx/conf.d/
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./conf/php.ini:/usr/local/etc/php/php.ini
      - ./www:/www/
      - ./log/php-fpm:/var/log/php-fpm
      - ./log/nginx:/var/log/nginx
      - ./mysql/data:/var/lib/mysql

  php:
    build:
      context: ./php
      dockerfile: dockerfile_php7w
    image: php7w
    container_name: phpfpm
    volumes_from:
      - vc_data
    ports:
      - "9000:9000"

  mysql:
    image: mysql:5.6.42
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Abcd123qwer...
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes_from:
      - vc_data
    ports:
      - "3306:3306"

  nginx:
    image: nginx:1.12.2
    container_name: nginx
    volumes_from:
      - vc_data
    links:
      - php
      - mysql
    ports:
      - "80:80"
